repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
      - id: check-toml
        name: Check Toml
      - id: check-ast
        name: Check AST
      - id: check-docstring-first
        name: Check docstring first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
        name: Check Yaml
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        args:
          - --application-directories=src
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
